language: julia

os:
  - linux

julia:
  - 1.3

notifications:
  email: false

after_success: skip

jobs:
  include:
    - stage: "Documentation"
      julia: 1.3
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.Registry.add(Pkg.Registry.RegistrySpec(url = "https://github.com/j-fu/PackageNursery.jl.git")); Pkg.instantiate(); Pkg.develop(PackageSpec(path=pwd()))'
        - julia --project=docs/ docs/make.jl
      after_success: skip

