name = "VTKView"
uuid = "63b67fce-66f7-11ea-1808-1361d8c55bf4"
authors = ["Juergen Fuhrmann <juergen.fuhrmann@wias-berlin.de>"]
version = "0.1.2"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
vtkfig_jll = "2bcdf5c0-6329-11ea-0b83-f5d1b57ecfa1"

[compat]
DocStringExtensions = "^0.8"
ForwardDiff = "^0.10"
julia = "^1.3"
vtkfig_jll = "0.23"
